### ISSUE TITLE
GitHub Actions - deploy to github.io

### ISSUE THREAD

**Issue by doradsoft** [doradsoft/html-flip-book#1]
stages:
.: npm i
./base: npm i
./base: npm run build
./react: npm i
./react/example: npm i
./react/example: npm run build
cp -r ./react/example/dist <github_io_project_page>

**Comment by HagegeR** [comment]
I'll need more access to make the action run

**Comment by HagegeR** [comment]
I'll use github.io from this repo directly

**Comment by HagegeR** [comment]
it seems like the build does not produce a valid html...

**Comment by doradsoft** [comment]
Please elaborate, or alternatively let's have a session so I can debug, because in my environment it does produce a valid HTML.

**Comment by doradsoft** [comment]
fixed in the PR, awaiting approval

**Comment by HagegeR** [comment]
fixed in the PR, awaiting approval
